config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root   'users#home'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, only:[:new, :create, :destroy, :edit, :show, :update]
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :state,  presence: true
  validates :limit,  presence: true
  validates :task,   presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy 
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
      # debugger
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def new
        @task = Task.new
    end

    def index
      @tasks = Task.all
    end

    def show
        @task = Task.find(params[:id])
    end

    def create
      @task = Task.new(task_params)
      @task.user_id = current_user.id
      if @task.save
        flash[:success] = "Create a new task"
        redirect_to user_url(current_user)
      else
        flash.now[:denger] = "Failed to cerate task."
        render 'new'
      end
    end

    def edit
        @task = Task.find(params[:id])
    end
    
    def update
      @task = Task.find(params[:id])
      if @task.update(task_params)
        flash[:success] = "Task updated."
        redirect_to user_url(@task.user_id)
      else
        flash[:danger] = "Failed to update task."
        render 'edit'
      end
    end

    def destroy
        @tasks = Task.all
        task = Task.find(params[:id])
        task.destroy
        render :index
    end

    private

    def task_params
        params.require(:task).permit(:state, :limit, :task)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only:[:edit, :update]
  before_action :correct_user, only:[:edit, :update]
  def home
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to YourTodolist!!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "User Updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

  def logged_in_user
    unless logged_in?
      flash[:denger] = "Please log in."
      redirect_to login_path
    end
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーをログイン
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # 現在ログイン中のユーザーを返す（いる場合）
  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end


  # 渡されたユーザーがカレントユーザーであればtrueを返す
  def current_user?(user)
    user && user == current_user
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
  def full_title(page_title='')
  base_title = "Otake's TodoList"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<p>cerated by Koki Otake</p>
<%= debug(params) if Rails.env.development? %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse id:logo">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "My Todolist", user_path(current_user) %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
      </ul>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>" ><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_task_error_messages.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@task.errors.count, "error") %>.
    </div>
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<div class ="form_group">
    <%= form_for(@task) do |f| %>
    <%= f.label 'limit' %>
    <%= f.date_field :limit %><br>
    
    <%= f.label 'task' %>
    <%= f.text_field :task %><br>
    
    <%= f.label 'state' %>
    <%= f.select :state, [["Todo", "Todo"], ["Doing", "Doing"],["Done", "Done"]], include_blank: "選択して下さい" %><br>
    <%= f.submit %>
</div>
<% end %>

app/views/tasks/_task_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @task, local: true) do |f| %>
      <%= render 'shared/task_error_messages' %>
      <%= f.label :limit %>
      <%= f.date_field :limit, class: 'form-control' %><br>
      
      <%= f.label :task %>
      <%= f.text_field :task, class: 'form-control' %><br>
      
      <%= f.label :state %><br>
      <%= f.select :state, [["Todo", "Todo"], ["Doing", "Doing"],["Done", "Done"]], include_blank: "選択して下さい" , class: 'form-control' %><br>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<% provide(:title,"編集") %>
<h1>Edit Task</h1>

<%= render 'task_form' %>

app/views/tasks/index.html.erb
<% provide(:title,"一覧") %>

<div class="container">
  <h1>Tasks</h1>
    <div class="row">
      <table class="table table-bordered">
        <tr>
          <th>state</th>
          <th>task</th>
          <th>limit</th>
          <th></th>
        </tr>
        <% @tasks.each do |t| %>
        <tr>
          <td><%= t.state %></td>
          <td><%= t.task %></td>
          <td><%= t.limit %></td>
          <td><%= link_to "編集", edit_task_path(t), class:"btn btn-success" %><%= link_to "削除", task_path(t), method: :delete, data:{ confirm: '本当に削除しますか?' }, class:"btn btn-danger"%></td>
        </tr>
        <% end %>
      </table>
    </div>
<%= link_to "新規", new_task_path, class: "btn btn-primary" %>
</div>

app/views/tasks/new.html.erb
<% provide(:title,"新規投稿") %>
<h1>Create New Task</h1>
  <%= render 'task_form' %>

app/views/tasks/show.html.erb
<% provide(:title,"詳細") %>
<tr>
    <td><%= @task.state %></td>
    <td><%= @task.task %></td>
    <td><%= @task.limit %></td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/user_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>


      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/home.html.erb
<h1 class="top-title">Otake's Sample App</h1>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/user_error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,"My Todolist") %>
<h1>My Todolist</h1>

<div class="container">
  <h3>Account</h3>
  <div>name ：<%= @user.name %></div>
  <div>email：<%= @user.email %></div>
  <%= link_to "Edit my account", edit_user_path %>
</div>


<div class="container">
  <h3>Tasks</h3>
    <div class="row">
      <table class="table table-bordered">
        <tr>
          <th>state</th>
          <th>task</th>
          <th>limit</th>
          <th></th>
        </tr>
        <% @tasks.each do |t| %>
        <tr>
          <td><%= t.state %></td>
          <td><%= t.task %></td>
          <td><%= t.limit %></td>
          <td><%= link_to "Edit", edit_task_path(t), class:"btn btn-success" %> <%= link_to "Destroy", task_path(t), method: :delete, data:{ confirm: '本当に削除しますか?' }, class:"btn btn-danger"%></td>
        </tr>
        <% end %>
      </table>
    </div>
<%= link_to "New task", new_task_path, class: "btn btn-primary" %>
</div>